# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import session_module.sessiondata_pb2 as sessiondata__pb2


class SessionDataServiceStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.GetSessionData = channel.unary_unary(
        '/SessionDataService/GetSessionData',
        request_serializer=sessiondata__pb2.SessionRequestInfo.SerializeToString,
        response_deserializer=sessiondata__pb2.ListsSessions.FromString,
        )
    self.PingSess = channel.unary_unary(
        '/SessionDataService/PingSess',
        request_serializer=sessiondata__pb2.PingSessRequest.SerializeToString,
        response_deserializer=sessiondata__pb2.PingSessResponse.FromString,
        )


class SessionDataServiceServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def GetSessionData(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def PingSess(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_SessionDataServiceServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'GetSessionData': grpc.unary_unary_rpc_method_handler(
          servicer.GetSessionData,
          request_deserializer=sessiondata__pb2.SessionRequestInfo.FromString,
          response_serializer=sessiondata__pb2.ListsSessions.SerializeToString,
      ),
      'PingSess': grpc.unary_unary_rpc_method_handler(
          servicer.PingSess,
          request_deserializer=sessiondata__pb2.PingSessRequest.FromString,
          response_serializer=sessiondata__pb2.PingSessResponse.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'SessionDataService', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
