# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: sessiondata.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='sessiondata.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x11sessiondata.proto\"+\n\rListsSessions\x12\x1a\n\x08sessions\x18\x01 \x03(\x0b\x32\x08.Session\"\x1f\n\x07Session\x12\x14\n\x0csession_item\x18\x01 \x03(\t\"(\n\x12SessionRequestInfo\x12\x12\n\nlast_hours\x18\x01 \x01(\x05\" \n\x10PingSessResponse\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\t\"\x11\n\x0fPingSessRequest2|\n\x12SessionDataService\x12\x35\n\x0eGetSessionData\x12\x13.SessionRequestInfo\x1a\x0e.ListsSessions\x12/\n\x08PingSess\x12\x10.PingSessRequest\x1a\x11.PingSessResponseb\x06proto3')
)




_LISTSSESSIONS = _descriptor.Descriptor(
  name='ListsSessions',
  full_name='ListsSessions',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='sessions', full_name='ListsSessions.sessions', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=21,
  serialized_end=64,
)


_SESSION = _descriptor.Descriptor(
  name='Session',
  full_name='Session',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='session_item', full_name='Session.session_item', index=0,
      number=1, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=66,
  serialized_end=97,
)


_SESSIONREQUESTINFO = _descriptor.Descriptor(
  name='SessionRequestInfo',
  full_name='SessionRequestInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='last_hours', full_name='SessionRequestInfo.last_hours', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=99,
  serialized_end=139,
)


_PINGSESSRESPONSE = _descriptor.Descriptor(
  name='PingSessResponse',
  full_name='PingSessResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='data', full_name='PingSessResponse.data', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=141,
  serialized_end=173,
)


_PINGSESSREQUEST = _descriptor.Descriptor(
  name='PingSessRequest',
  full_name='PingSessRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=175,
  serialized_end=192,
)

_LISTSSESSIONS.fields_by_name['sessions'].message_type = _SESSION
DESCRIPTOR.message_types_by_name['ListsSessions'] = _LISTSSESSIONS
DESCRIPTOR.message_types_by_name['Session'] = _SESSION
DESCRIPTOR.message_types_by_name['SessionRequestInfo'] = _SESSIONREQUESTINFO
DESCRIPTOR.message_types_by_name['PingSessResponse'] = _PINGSESSRESPONSE
DESCRIPTOR.message_types_by_name['PingSessRequest'] = _PINGSESSREQUEST
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ListsSessions = _reflection.GeneratedProtocolMessageType('ListsSessions', (_message.Message,), {
  'DESCRIPTOR' : _LISTSSESSIONS,
  '__module__' : 'sessiondata_pb2'
  # @@protoc_insertion_point(class_scope:ListsSessions)
  })
_sym_db.RegisterMessage(ListsSessions)

Session = _reflection.GeneratedProtocolMessageType('Session', (_message.Message,), {
  'DESCRIPTOR' : _SESSION,
  '__module__' : 'sessiondata_pb2'
  # @@protoc_insertion_point(class_scope:Session)
  })
_sym_db.RegisterMessage(Session)

SessionRequestInfo = _reflection.GeneratedProtocolMessageType('SessionRequestInfo', (_message.Message,), {
  'DESCRIPTOR' : _SESSIONREQUESTINFO,
  '__module__' : 'sessiondata_pb2'
  # @@protoc_insertion_point(class_scope:SessionRequestInfo)
  })
_sym_db.RegisterMessage(SessionRequestInfo)

PingSessResponse = _reflection.GeneratedProtocolMessageType('PingSessResponse', (_message.Message,), {
  'DESCRIPTOR' : _PINGSESSRESPONSE,
  '__module__' : 'sessiondata_pb2'
  # @@protoc_insertion_point(class_scope:PingSessResponse)
  })
_sym_db.RegisterMessage(PingSessResponse)

PingSessRequest = _reflection.GeneratedProtocolMessageType('PingSessRequest', (_message.Message,), {
  'DESCRIPTOR' : _PINGSESSREQUEST,
  '__module__' : 'sessiondata_pb2'
  # @@protoc_insertion_point(class_scope:PingSessRequest)
  })
_sym_db.RegisterMessage(PingSessRequest)



_SESSIONDATASERVICE = _descriptor.ServiceDescriptor(
  name='SessionDataService',
  full_name='SessionDataService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=194,
  serialized_end=318,
  methods=[
  _descriptor.MethodDescriptor(
    name='GetSessionData',
    full_name='SessionDataService.GetSessionData',
    index=0,
    containing_service=None,
    input_type=_SESSIONREQUESTINFO,
    output_type=_LISTSSESSIONS,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='PingSess',
    full_name='SessionDataService.PingSess',
    index=1,
    containing_service=None,
    input_type=_PINGSESSREQUEST,
    output_type=_PINGSESSRESPONSE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_SESSIONDATASERVICE)

DESCRIPTOR.services_by_name['SessionDataService'] = _SESSIONDATASERVICE

# @@protoc_insertion_point(module_scope)
